///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String carsharing = 'assets/carsharing.png';
  static const String logisticsDelivery = 'assets/logistics-delivery.png';
  static const String transportation = 'assets/transportation.png';
  static const String vehicles = 'assets/vehicles.png';

}
